# Generated by Django 5.0.4 on 2024-04-24 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nin',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='villages.village')),
            ],
        ),
    ]
