### List Villages
GET http://localhost:8000/api/villages/

### Create Village
POST http://localhost:8000/api/villages/ HTTP/1.1
Content-Type: application/json

{
    "name": "Iwakagure"
}



### Delete Village
DELETE http://localhost:8000/api/villages/e5a2d8f3-7098-40bf-85b1-2a33950cce2f